'use client'
import { Inter } from "next/font/google";
import 'normalize.css/normalize.css'
import '@/styles/globals.css'
import styles from './layout.module.css'

import { useState } from 'react'

import React from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import TaskDisplayBox from "@/components/TaskDisplayBox";
import NavBar from "@/components/NavBar";


const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

export default function RootLayout({ children}) {
  const [activeTab, setActiveTab] = useState('allTask');
  return (
    <html lang="en" className={styles.html}>
      <body className={inter.className + ' ' + styles.body}>
        <main>
          <div className={styles.wrapper}>
            <ToastContainer
              position="top-right"
              autoClose={2000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark">
            </ToastContainer>
            {/*children*/}
            <NavBar activeTab={activeTab} setActiveTab={setActiveTab}/>
            <TaskDisplayBox activeTab={activeTab} setActiveTab={setActiveTab}/>
          </div>
        </main> 
      </body>
    </html>
  );
}
